import { CarItem } from "../types";

export const data: CarItem[] = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2022,
    type: "Sedan",
    description: "A reliable and fuel-efficient sedan with a sleek design and advanced safety features.",
    features: [
      "Leather seats",
      "Sunroof",
      "Bluetooth connectivity",
      "Backup camera",
      "Adaptive cruise control",
    ],
    availability: "In Stock",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 28000,
  },
  {
    id: 2,
    make: "Ford",
    model: "Mustang",
    year: 2021,
    type: "Coupe",
    description: "A powerful and iconic muscle car with a roaring V8 engine and sporty design.",
    features: [
      "V8 engine",
      "Sport-tuned suspension",
      "Leather-wrapped steering wheel",
      "Dual exhaust",
      "Touchscreen infotainment",
    ],
    availability: "In Stock",
    image: "https://images.unsplash.com/photo-1603553329474-99f95f35394f?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 45000,
  },
  {
    id: 3,
    make: "Tesla",
    model: "Model 3",
    year: 2023,
    type: "Sedan",
    description: "A fully electric sedan with cutting-edge technology and impressive performance.",
    features: [
      "Autopilot",
      "Electric powertrain",
      "Minimalist interior",
      "Large touchscreen display",
      "Over-the-air updates",
    ],
    availability: "In Stock",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?q=80&w=2759&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 50000,
  },
  {
    id: 4,
    make: "Jeep",
    model: "Wrangler",
    year: 2022,
    type: "SUV",
    description: "An off-road capable SUV designed for adventure and rugged terrain.",
    features: [
      "4x4 drivetrain",
      "Removable doors and roof",
      "Off-road tires",
      "High ground clearance",
      "Touchscreen infotainment",
    ],
    availability: "Limited Stock",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?q=80&w=2759&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 39000,
  },
  {
    id: 5,
    make: "BMW",
    model: "X5",
    year: 2023,
    type: "SUV",
    description: "A luxury SUV with high-performance capabilities and premium features.",
    features: [
      "All-wheel drive",
      "Leather interior",
      "Panoramic sunroof",
      "Advanced driver-assist features",
      "Premium sound system",
    ],
    availability: "In Stock",
    image: "https://images.unsplash.com/photo-1609184166822-bd1f1b991a06?q=80&w=2699&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 65000,
  },
  {
    id: 6,
    make: "Chevrolet",
    model: "Silverado",
    year: 2022,
    type: "Truck",
    description: "A tough and reliable pickup truck with high towing capacity and durability.",
    features: [
      "V8 engine",
      "4x4 capability",
      "Large cargo bed",
      "Towing package",
      "Infotainment system with Apple CarPlay & Android Auto",
    ],
    availability: "In Stock",
    image: "https://images.unsplash.com/photo-1647698848537-c72bd8049ed0?q=80&w=2676&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: 42000,
  },
];
